version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: nyc_finance
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  etl:
    build: ./etl
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/nyc_finance
volumes:
  pgdata:
